### ISSUE TITLE
Duplicate field `load`.Lua Diagnostics.(duplicate-set-field) linting warning.

### ISSUE THREAD

**Issue by joshuarichards001** [usysrc/LICK#13]
Hey mate,

I'm getting the linting warning 

> "Duplicate field `load`.Lua Diagnostics.(duplicate-set-field)"

(also present on update and draw too)  

when adding lick to my project. 

I'm guessing it's from the [Lua Language Server](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) extension so it might just be a matter of ignoring the linter but it would be good to get your perspective if there's a more elegant approach. 

Cheers!

**Comment by usysrc** [comment]
Hey @joshuarichards001 

could you provide a minimal example?

**Comment by joshuarichards001** [comment]
Here's the simple repo I'm working with: https://github.com/joshuarichards001/lua-love-game

Sorry if things aren't formatted correctly, not sure how to work with packages in Lua haha.

Also I ignored the warnings at the top of `main.lua` so you'll need to remove that with the Lua VSCode extension to replicate.

**Comment by usysrc** [comment]
Hey @joshuarichards001 

you should be able to just delete the main.lua in the `packages/lick` folder if you are not using it. Then the duplicate field diagnostic will go away.
