### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by zorggn** [usysrc/LICK#7]
To claim that this works with löve 11.3, you need to fix two things;
One, the debug print color should be in the range of [0,1] float instead of [0,255] ints since color values were normalized.
Two, as per the wiki page on love.run, you need to clear to the set backgroundcolor: `
love.graphics.clear(love.graphics.getBackgroundColor())`

**Comment by jikkujose** [comment]
Yes, this caused me a lot of head scratching. If you don't have the time, I am happy to give a PR for this so that others won't stumble here. But other than this, pretty good work! Cheers!

**Comment by usysrc** [comment]
@jikkujose a PR would be greatly appreciated.

**Comment by usysrc** [comment]
Thank you for you suggestions. I implemented this in 3d0b5624ef10926c471ec1495cda947ac3df837c
