### ISSUE TITLE
What license is LICK under?

### ISSUE THREAD

**Issue by pianohacker** [usysrc/LICK#8]
Which license is this under? I love this library and would like to use/modify it in my MPL-2.0 project if possible.

**Comment by pianohacker** [comment]
@usysrc , checking in to see if you can clarify.

**Comment by usysrc** [comment]
It is now under MIT License https://github.com/usysrc/LICK/commit/54395b4e57c9b6d76307cfc561df043223575d6e

**Comment by pianohacker** [comment]
Thank you!
