### ISSUE TITLE
Option to listen folder or several files

### ISSUE THREAD

**Issue by 3xau1o** [usysrc/LICK#9]
Nice tool!
Currently reload trigger only when main.lua file changes, so need to save a dummy change on main.lua everytime another script is changed to reload all other scripts

```lua
function love.load()
    require("script")
    require("test")
end
```

is it a bad idea to listed to changes in multiple files?

**Comment by usysrc** [comment]
Hey @3xau1o can you take a look at the PR in #10 and tell me if that fixes your problem?

**Comment by 3xau1o** [comment]
@usysrc 
tested by copying lick.lua from your PR to my project and yes, it does the job
* when project starts screen is black, after saving a lua file change, game appeared
* is it possible to add an option to specify other file extensions, like .tl (teal)

**Comment by usysrc** [comment]
Thanks, I fixed the first point and added an issue for the second. Please continue the discussion there.
